ports{
  intakeArmMotor = 18
}

intakeArmMotor{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    useOffset = false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    #min is the farthest the arm can extend
    #max is the farthest the arm can retract
    minArmAngle=11.88
    maxArmAngle=120.6
}

kpa = 0.0025
kia = 0
kda = 0
#these are in degrees, the actual values on the encoder are
#0.326 and 0.046 (0.335 max, 0.033 min)
retractArm = 117.36
extendArm = 16.56
offset = 9