ports{
  intakeArmMotor = 18
}

intakeArmMotor{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    #min is the farthest the arm can extend
    #max is the farthest the arm can retract
    minArmAngle=0
    maxArmAngle=180
}

kpa = 0.005
kia = 0
kda = 0
#these are in degrees, the actual values on the encoder are
#0.3 and 0
retractArm = 108
extendArm = 0
offset = 0