ports{
  intakeArmMotor = 18
}

intakeArmMotor{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    minArmAngle=0
    maxArmAngle=359
}

kpa = 0.005
kia = 0
kda = 0
retractArm = 30
extendArm = 60
offset = 0