ports{
  extender = 19
  rotator = 20
}

extender{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}
rotator{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    minAngle=0
    maxAngle=359
}

#all of these are placeholders...
#no clue what the units for WP should be tbh
#extension ones should probably be measured in rotations, not degrees
#rotation ones HAVE been replaced with the gyro as the setpoint
#if we do decide on that, there should be another rotation command
#which moves it to 0, just in case yknow
#we have a max and min value for rotation of the motor as a failsafe
#all the PID, MOTM, tolerances, IZ, WP, and MO values are arbitrary
#considering they were from move using encoder
#may want to consider adding a feed forward value
#we have an FF class, no idea how it works, very weird class
#but we may need it for the climber rotation
#potentially look at gio's arm test bench code for how to add FF
#CUAP is used for going to a potentially different climbing value in auto
#we aren't sure whether we want to go fully up in auto
#MO will DEFINITELY have to be changed...
ShortClimberExtend {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=30
    maxOutput=0.3
}
LongClimberExtend {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=60
    maxOutput=0.3
}
ClimberRetract {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=0
    maxOutput=0.3
}
ClimbUp {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=170
    maxOutput=0.3
    minMotorRotation=45
    maxMotorRotation=315
}
ClimbUpAutoPosition {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=160
    maxOutput=0.3
    minMotorRotation=45
    maxMotorRotation=315
}
ClimbDown {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=0
    maxOutput=0.3
    minMotorRotation=45
    maxMotorRotation=315
}