ports{
  extender = 23
  rotator = 24
}

extender{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}
rotator{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    minAngle=0
    maxAngle=359
}
