ports{
  hopperFrontBeltsMotor = 99
  hopperBackBeltsMotor = 99
  #should go unused.
}

hopperFrontBeltsMotor{
    inverted=false
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}

hopperBackBeltsMotor{
    inverted=false
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}