ports{
  intakeRollersMotor = 23
}

intakeRollersMotor{
    inverted=false
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}