ports{
  leaderMotor = 23
  followerMotor = 22 #unknown value
}

leaderMotor{
    inverted=false
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=false
    rampRate = 0.1
    canBus = "rio"
    enableFOC = false
}
followerMotor{
    inverted=true
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=false
    rampRate = 0.1
    isFollower = true
    leader = 23
    canBus = "rio"
    enableFOC = false
}