subsystems {
  ejectbelt{}
<<<<<<< Updated upstream
  intakerollers{}
  ahi{}
  shooter{}
  swervedrivetrain{}
  WS2812LEDs {}
=======
  #intakerollers{}
  #ahi{}
  #shooter{}
  swervedrivetrain{}
  #WS2812LEDs {}
>>>>>>> Stashed changes
}