sensors {
   
}

pigeon {
    id=2
    canBus = "DriveTrainRAWR"
}

photonvision {
    useVisionForPose = true
    useAndyMarkField = false
    numberOfCameras = 2
    cameraName1 = OV9281-1mp-120fps-13
    cameraName2 = OV9281-1mp-120fps-14
   # 13 is the back camera  
    OV9281-1mp-120fps-13 {
        cameraOffsetToCenterInInches = -11.5555
        cameraOffsetToCenterInInchesY = -13.5
        cameraHeightInInches = 19.625
        cameraRollInDegrees = 0
        cameraPitchInDegrees = 0
        cameraYawInDegrees = 270
    }
    # 14 is the front camera
    OV9281-1mp-120fps-14 {
        cameraOffsetToCenterInInches = -11.566
        cameraOffsetToCenterInInchesY = 13.5
        cameraHeightInInches = 19.6875
        cameraRollInDegrees = 0
        cameraPitchInDegrees = 0
        cameraYawInDegrees = 90
    }
}