sensors {
    tof0 {
        port=15
        rangingMode=Short
        sampleTime=24
        rangeOfInterest.topLeftX=8
        rangeOfInterest.topLeftY=8
        rangeOfInterest.bottomRightX=12
        rangeOfInterest.bottomRightY=12
        sensorOffset_inches=0
        numberOfTaps=10
        useLinearFilter=true
        facingAngle=270
    }
    tof1 {
        port=16
        rangingMode=Short
        sampleTime=24
        rangeOfInterest.topLeftX=8
        rangeOfInterest.topLeftY=8
        rangeOfInterest.bottomRightX=12
        rangeOfInterest.bottomRightY=12
        sensorOffset_inches=0
        numberOfTaps=20
        useLinearFilter=false
        facingAngle=270
    }
    tof2 {
        port=17
        rangingMode=Short
        sampleTime=24
        rangeOfInterest.topLeftX=8
        rangeOfInterest.topLeftY=8
        rangeOfInterest.bottomRightX=12
        rangeOfInterest.bottomRightY=12
        sensorOffset_inches=0
        numberOfTaps=20
        useLinearFilter=false
        facingAngle=270
    }
}

pigeon {
    id=2
}
