ports{
  leaderMotor = 24
  followerMotor = 25
}

leaderMotor{
    inverted=false
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}
followerMotor{
    inverted=true
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    isFollower = true
    leader = 24
}
#ALL of these values are taken from 2024 and are untested.
runshooterwheelvelocity{
    p=0.0001
    i=0
    d=0
}
tolerance=225
#these pairs are (RPM, Kvalue)
shooterTargetRPMAndKValues=[
    1000, 0.2
]
#these pairs are (RPM, Pvalue)
shooterTargetRPMandPValues=[
    1000, 0.0001
]
#these pairs are (distance in inches, RPM)
shotShootingRPM=[
    # close shot - measured distance 36
    36, 3250
]