ports{
  leaderMotor = 24
  followerMotor = 25
}

leaderMotor{
    inverted=false
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=false
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}
followerMotor{
    inverted=true
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=false
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    isFollower = true
    leader = 24
}
#The RSWV, STRPMAPV, and SSRPM are all from 2024.
#they may be edited in the future for better PID'ing for the 2026 bot.
runshooterwheelvelocity{
    p=0.00015
    i=0
    d=0
}
tolerance=325
#these pairs are (RPM, Kvalue)
shooterTargetRPMAndKValues=[
    500, 0.087,
    1000, 0.17,
    1500, 0.253,
    2000, 0.337,
    2500, 0.42,
    3000, 0.505,
    3500, 0.59,
    4000, 0.675,
    4500, 0.76,
    5000, 0.846,
    5500, 0.933,
    5750, 0.973
]
#these pairs are (RPM, Pvalue)
shooterTargetRPMandPValues=[
    1000, 0.0001
]
#these pairs are (distance in inches, RPM)
shotShootingRPM=[
    65, 3550,
    75, 3650,
    85, 3700,
    95, 3750,
    105, 3800,
    115, 3900,
    125, 4000,
    135, 4100,
    145, 4275,
    155, 4375,
    165, 4475,
    205, 4850
]
#arbitrary
shuttleRPM=4500