ports{
  shooterMotor = 24
}

shooterMotor{
    inverted=false
    hasAbsoluteEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    wantedRPM = 500.00
}
kp = 0.0
ki = 0.0
kd = 0.0