@startuml SubsystemStates
[*]-->WFC

State "WAIT_FOR_CORAL" as WFC{
  WFC: Coral Motor: STOP
  WFC: Coral Motor Speed: 0
}
WFC-->WFC: -!inSense & \n !ejSense
WFC-->IC: - inSense & \n !ejSense
WFC-->HC: - !inSense & \n ejSense

State "INTAKE_CORAL" as IC{
  IC: Coral Motor: FORWARD
  IC: Coral Motor Speed: INTAKE SPEED
}  
IC-->IC: - inSense & \n !ejSense
IC-->PC: - inSense & \n ejSense

State "POSITION_CORAL" as PC{
  PC: Coral Motor: FORWARD
  PC: Coral Motor Speed: POSITION SPEED
}
PC-->PC: - inSense & \n ejSense
PC-->HC: - !inSense & \n ejSense

State "HOLD_CORAL" as HC{
  HC: Coral Motor: stop
  HC: Coral Motor Speed: 0
}
HC-->HC: - !inSense & \n ejSense
HC-->PC: - inSense & \n ejSense
HC-->EC: - EJECT_SIGNAL

State "EJECT_CORAL" as EC{
  EC: Coral Motor: stop
  EC: Coral Motor Speed: EJECT SPEED
}
EC-->EC: - !inSense & \n ejSense
EC-->PFE: - !inSense & \n !ejSense

State "PAUSE_FOR_EJECT" as PFE{
  PFE: Coral Motor: 
  PFE: Coral Motor Speed: 0
}
PFE-->PFE: - Pause X Loops
PFE-->WFC: - > X Loops
