ports{
  extender = 19
  rotator = 20
}

extender{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}
rotator{
    inverted=false
    hasAbsoluteEncoder=true
    absoluteEncoderInverted=false
    absoluteEncoderZeroOffset=0
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
    minAngle=0
    maxAngle=359
}

ShortClimberExtend {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=30
    maxOutput=0.3
}
LongClimberExtend {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=30
    maxOutput=0.3
}
ClimberRetract {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=30
    maxOutput=0.3
}
ClimbUp {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=30
    maxOutput=0.3
}
ClimbDown {
    Kp = 0.01
    Ki = 0
    Kd = 0
    minOutputToMove = 0.02
    positionTolerance=0.095
    velocityTolerance=3
    iZone=2
    wantedPosition=30
    maxOutput=0.3
}