sensors {
   
}

pigeon {
    id=2
}

photonvision {
    useVisionForPose = true
    useAndyMarkField = true
    numberOfCameras = 2
    cameraName1 = OV9281-1mp-120fps-11
    cameraName2 = OV9281-1mp-120fps-6
    OV9281-1mp-120fps-11 {
        cameraOffsetToCenterInInches = 5.3125
        cameraOffsetToCenterInInchesY = -14.5
        cameraHeightInInches = 22.25
        cameraRollInDegrees = 0
        cameraPitchInDegrees = 0
        cameraYawInDegrees = 270
    }

       OV9281-1mp-120fps-6 {
        cameraOffsetToCenterInInches = -13.0
        cameraOffsetToCenterInInchesY = -14.5
        cameraHeightInInches = 22.25
        cameraRollInDegrees = 0
        cameraPitchInDegrees = 0
        cameraYawInDegrees = 270
    }
}