package frc.robot.subsystems.feeder;

public enum FeederStates {
  UNKNOWN, EMPTY, ONE_LOADING, ONE_LOADED, SECOND_LOADING_1, SECOND_LOADING_2, SECOND_LOADING_3, SECOND_LOADED,
  THIRD_LOADING_1, THIRD_LOADING_2, THIRD_LOADING_3, THIRD_LOADED;
}