ports{
  intakeArmMotor = 2
  hopperExtensionMotor = 3
}

intakeArmMotor{
    inverted=false
    hasEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}

hopperExtensionMotor{
    inverted=false
    hasEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}
