ports{
  ejectBeltMotor = 5
}

ejectBeltMotor{
    inverted=false
    hasEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}
