ports{
  hopperFrontBeltsMotor = 6
  hopperBackBeltsMotor = 7
}

hopperFrontBeltsMotor{
    inverted=false
    hasEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}

hopperBackBeltsMotor{
    inverted=false
    hasEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}