ports{
  intakeRollersMotor = 9
}

intakeRollersMotor{
    inverted=false
    hasEncoder=false
    encoderInverted=false
    currentLimit=60
    brakeMode=true
    hasForwardLimitSwitch = false
    hasReverseLimitSwitch = false
}